version: 0.2

phases:
  install:
    commands:
      # install Node 12
      # install npm
      - yum install -y gcc-c++ make
      - curl --silent --location https://rpm.nodesource.com/setup_12.x | bash - 
      - yum -y install nodejs
      - npm install -g npm@latest
  pre_build:
    commands:
      # install dependencies
      - npm install
      - npm install --prefix client
  build:
    commands:
      # build
      - npm run --prefix client build
