version: 0.2

phases:
  install:
    commands:
      # install Node 12
      # install npm
      - pip install --upgrade awscli
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install nodejs

  pre_build:
    commands:
      # install dependencies
      - npm install --production
  build:
    commands:
      # build static files
      - mkdir -p ./client/node_modules
      - npm install --prefix client --production
      - npm run build --prefix client

artifacts:
  files:
    - '**/*'
  base-directory: 'client/build'

      
