version: 0.2

phases:
  install:
    commands:
      # install Node 12
      # install npm
      - pip install --upgrade awscli
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install nodejs

  pre_build:
    commands:
      # install dependencies
      - npm install
      - npm install --prefix client
  build:
    commands:
      # build
      - npm run --prefix client build
