version: 0.2

phases:
  install:
    commands:
      # upgrade AWS CLI
      - pip install --upgrade awscli
      # install Node 12
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install nodejs

  pre_build:
    commands:
      # install server dependencies
      - npm install --production
  build:
    commands:
      # install client dependencies build static files
      - mkdir -p ./client/node_modules
      - npm install --prefix client --production
      - npm run build --prefix client

artifacts:
  files:
    - '**/*'

      
